# frozen_string_literal: true

module SoftwareChallengeClient
  require './lib/software_challenge_client/board.rb'
  require './lib/software_challenge_client/client_interface.rb'
  require './lib/software_challenge_client/color.rb'
  require './lib/software_challenge_client/condition.rb'
  require './lib/software_challenge_client/coordinate_set.rb'
  require './lib/software_challenge_client/coordinates.rb'
  require './lib/software_challenge_client/debug_hint.rb'
  require './lib/software_challenge_client/field.rb'
  require './lib/software_challenge_client/game_rule_logic.rb'
  require './lib/software_challenge_client/game_state.rb'
  require './lib/software_challenge_client/has_hints.rb'
  require './lib/software_challenge_client/invalid_move_exception.rb'
  require './lib/software_challenge_client/logging.rb'
  require './lib/software_challenge_client/network.rb'
  require './lib/software_challenge_client/piece.rb'
  require './lib/software_challenge_client/piece_shape.rb'
  require './lib/software_challenge_client/player.rb'
  require './lib/software_challenge_client/player_type.rb'
  require './lib/software_challenge_client/protocol.rb'
  require './lib/software_challenge_client/rotation.rb'
  require './lib/software_challenge_client/runner.rb'
  require './lib/software_challenge_client/set_move.rb'
  require './lib/software_challenge_client/skip_move.rb'
  require './lib/software_challenge_client/util/constants.rb'
  require './lib/software_challenge_client/version.rb'
end
