# frozen_string_literal: true
module SoftwareChallengeClient
  require_relative 'software_challenge_client/board.rb'
  require_relative 'software_challenge_client/client_interface.rb'
  require_relative 'software_challenge_client/color.rb'
  require_relative 'software_challenge_client/condition.rb'
  require_relative 'software_challenge_client/coordinates.rb'
  require_relative 'software_challenge_client/debug_hint.rb'
  require_relative 'software_challenge_client/field.rb'
  require_relative 'software_challenge_client/game_rule_logic.rb'
  require_relative 'software_challenge_client/game_state.rb'
  require_relative 'software_challenge_client/has_hints.rb'
  require_relative 'software_challenge_client/invalid_move_exception.rb'
  require_relative 'software_challenge_client/logging.rb'
  require_relative 'software_challenge_client/move.rb'
  require_relative 'software_challenge_client/network.rb'
  require_relative 'software_challenge_client/piece.rb'
  require_relative 'software_challenge_client/piece_type.rb'
  require_relative 'software_challenge_client/player.rb'
  require_relative 'software_challenge_client/protocol.rb'
  require_relative 'software_challenge_client/runner.rb'
  require_relative 'software_challenge_client/team.rb'
  require_relative 'software_challenge_client/util/constants.rb'
  require_relative 'software_challenge_client/version.rb'
end
